export const INPUT_TYPE_TEXT = "text"
export const INPUT_TYPE_EMAIL = "email"
export const INPUT_TYPE_PASSWORD = "password"
export const INPUT_TYPE_DATE = "date"
export const INPUT_TYPE_RADIO = "radio"