export const INPUT_LABEL_FNAME = "First Name"
export const INPUT_LABEL_LNAME = "Last Name"
export const INPUT_LABEL_EMAIL = "Email Address"
export const INPUT_LABEL_PASSWORD = "Choose Password"
export const INPUT_LABEL_CONFIRM_PASSWORD = "Confirm Password"
export const INPUT_LABEL_BIRTHDATE = "Birthdate"
export const INPUT_LABEL_PHONE = "Phone Number"
export const INPUT_LABEL_COUNTRY = "Country"
export const INPUT_LABEL_ZIPCODE = "Zip/Postal Code"
export const INPUT_LABEL_MONTH = "Month"
export const INPUT_LABEL_DAY = "Day"
export const INPUT_LABEL_YEAR = "Year"
export const INPUT_LABEL_PHONE_SECONDARY = "Lorem ipsum dolor."


